### ISSUE TITLE
Upgrading to version 0.14.0 results in undefined method `urls' for OEmbed::Providers::Instagram:Class

### ISSUE THREAD

**Issue by joostvanrijn** [ruby-oembed/ruby-oembed#77]
We register providers in an initializer as follows:
```
OEmbed::Providers.register(OEmbed::Providers::Youtube,
                           OEmbed::Providers::Vimeo,
                           OEmbed::Providers::Flickr,
                           OEmbed::Providers::Instagram,
                           OEmbed::Providers::SoundCloud)
```

After upgrading this gem to 0.14.0 the Rails server won't boot anymore. Inspecting the providers array gives:

```
[#<OEmbed::Provider:0x00007fdfd6b83518
  @endpoint="https://www.youtube.com/oembed?scheme=https",
  @format="json",
  @urls=
   [/^http:\/\/([^\.]+\.)?youtube\.com\/(.*?)/, /^https:\/\/([^\.]+\.)?youtube\.com\/(.*?)/, /^http:\/\/([^\.]+\.)?youtu\.be\/(.*?)/, /^https:\/\/([^\.]+\.)?youtu\.be\/(.*?)/]>,
 #<OEmbed::Provider:0x00007fdfd84c15e8
  @endpoint="https://vimeo.com/api/oembed.{format}",
  @format="json",
  @urls=[/^http:\/\/([^\.]+\.)?vimeo\.com\/(.*?)/, /^https:\/\/([^\.]+\.)?vimeo\.com\/(.*?)/]>,
 #<OEmbed::Provider:0x00007fdfdcfc14f8
  @endpoint="https://www.flickr.com/services/oembed/",
  @format="json",
  @urls=[/^http:\/\/([^\.]+\.)?flickr\.com\/(.*?)/, /^https:\/\/([^\.]+\.)?flickr\.com\/(.*?)/, /^http:\/\/flic\.kr\/(.*?)/, /^https:\/\/flic\.kr\/(.*?)/]>,
 OEmbed::Providers::Instagram,
 #<OEmbed::Provider:0x00007fdfdf185030
  @endpoint="https://soundcloud.com/oembed",
  @format=:json,
  @urls=[/^http:\/\/([^\.]+\.)?soundcloud\.com\/(.*?)/, /^https:\/\/([^\.]+\.)?soundcloud\.com\/(.*?)/]>,
 #<OEmbed::Provider:0x00007fdfd6bfc260
  @endpoint="https://web.microsoftstream.com/oembed/",
  @format="json",
  @urls=[/^https:\/\/([^\.]+\.)?microsoftstream\.com\/video\/(.*?)/, /^https:\/\/([^\.]+\.)?microsoftstream\.com\/channel\/(.*?)/]>]
```

After which an `undefined method 'urls' for OEmbed::Providers::Instagram:Class` is thrown

**Comment by metavida** [comment]
Ah ha! Thanks for the detailed report! I know that version 0.14.0 introduced the concept of `access_tokens` for the `Instagram` provider (see https://github.com/ruby-oembed/ruby-oembed/blob/v0.14.0/README.md#providers-requiring-an-access-token ). 

PR #75 focused on injecting the access_tokens via `OEmbed::Providers.register_all`, so it's quite possible that we missed a case, registering Instagram or Facebook providers via `OEmbed::Providers.register` like you are.

By any chance, does the error go away if you set the `OEMBED_FACEBOOK_TOKEN` environment variable? (Even if it's just a made up, non-blank value)

**Comment by metavida** [comment]
Ok, I **think** I understand the breaking change now.

In earlier versions (e.g. 0.13.1) `OEmbed::Providers::Instagram` was an **instance** of `OEmbed::Provider`, that was instantiated when the gem loaded, here: https://github.com/ruby-oembed/ruby-oembed/blob/8ed6378b220c11e33559b544284961ac2807e022/lib/oembed/providers.rb#L206

In version 0.14.0 we changed the behavior so that `OEmbed::Providers::Instagram` is a **class** that _inherits_ from `OEmbed::Provider` but that needs to be instantiated **with** an `access_token` before it's used! Here's an example of it being instantiated within the `register_all` call stack: https://github.com/ruby-oembed/ruby-oembed/blob/72c8076f9c710564bd446748b7325f118692e432/lib/oembed/providers.rb#L143

# What can I do to fix my app today?

### Option A

I believe if you change your code, as follows, you can get your app starting up with version 0.14.0 today:
```
OEmbed::Providers.register(OEmbed::Providers::Youtube,
                           OEmbed::Providers::Vimeo,
                           OEmbed::Providers::Flickr,
                           OEmbed::Providers::Instagram.new(access_token: @my_facebook_token),
                           OEmbed::Providers::SoundCloud)
```
Of course you're going to have to get a Instagram/Facebook access token [by following these instructions](https://developers.facebook.com/docs/instagram/oembed#access-tokens), but that was a requirement as of October 24th, 2020 anyway, as reported in #74 

### Option B

Wait until I figure out how to fix this and release version 0.14.1 that is fully backwards compatible with older versions (and hopefully, maybe somehow **also** compatible with 0.14.0? 🤞 ). Since this project is something I do in my free time & since 2020 ... _waves hands at the world_ consumes a lot of my time and attention, I, unfortunately, can't commit to a specific timeline, but will do my best to keep this on my radar and am very much open to PRs!

**Comment by metavida** [comment]
Great news! I just [release version 0.15.0](https://rubygems.org/gems/ruby-oembed/versions/0.15.0) which resolves this bug! There are now 2 recommended ways of custom-registering your Instagram provider. You can either set its token via env var:
```ruby
ENV['OEMBED_FACEBOOK_TOKEN'] #=> 'my-access-token'
OEmbed::Providers.register(OEmbed::Providers::Flickr,
                           OEmbed::Providers::Instagram)
```
or by set its `access_token` directly:
```ruby
OEmbed::Providers::Instagram.access_token = @my_facebook_token
OEmbed::Providers.register(OEmbed::Providers::Flickr,
                           OEmbed::Providers::Instagram)
```

If you changed your app to call `OEmbed::Providers::Instagram.new` **please switch to one of the two above method** because the `Instagram.new` method **is deprecated** and will be removed in a future version of the ruby-oembed gem.

Thanks for reporting this issue & happy new year!
